<?php
/**
 * @file
 * The List Unsubscribe module.
 */

/**
 * Implements hook_menu().
 */
function list_unsubscribe_menu() {
  $items = array();
  $items['list-unsubscribe'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('list_unsubscribe_unsubscribe_email'),
    'description' => 'Unsubscribe from all email notifications',
    'access callback' => TRUE,
  );
  $items['list-unsubscribe/%'] = array(
    'page callback' => 'list_unsubscribe_unsubscribe_email',
    'description' => 'Callback for the "unsubscribe" link in emails',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_mail_alter().
 */
function list_unsubscribe_mail_alter(&$message) {
  // Checks if the email recipient was unsubscribed 
  if(_list_unsubscribe_email_check($message['to'])) {
    $message['send'] = FALSE; // This prevents the email from being sent
  }
}
